config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # verb '/path', to: 'controller_name#action'


  # CRUD
  # CREATE
  # 2 request
  # a get request to get a form, an empty instance of the restaurant model
  get '/restaurants/new', to: 'restaurants#new'
  # a post request to save the restauranst instance in the DB passing the params of the user
  post '/restaurants', to: 'restaurants#create'

  # READ ALL
  get '/restaurants', to: 'restaurants#index'
  # READ ONE
  get '/restaurants/:id', to: 'restaurants#show', as: :restaurant

  # UPDATE
  # edit => form
  get '/restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant
  # update => change the db
  patch '/restaurants/:id', to: 'restaurants#update'

  # DELETE
  delete '/restaurants/:id', to: 'restaurants#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true

  # def initialize(attributes = {})
  # end

  # def save
  # end

  # def self.all
  # end

  # def self.find
  #   DB.execute("SELECT * FROM restaurants WHERE id = ?", #{id})
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit]
  def index
    @restaurants = Restaurant.all
  end

  def show
    # raise
    # @restaurant = Restaurant.find(params[:id])
  end

  def destroy
    restaurant = Restaurant.find(params[:id])
    restaurant.destroy
    redirect_to restaurants_path
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    # raise (create is the same as new +save)
    # raise
    # restaurant = Restaurant.create(name: params[:name],address: params[:address], stars: params[:stars])
    # restaurant = Restaurant.create(params[:restaurant])
    restaurant = Restaurant.create(restaurant_strong_params)
    redirect_to restaurant_path(restaurant)
  end

  def edit
    # raise
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    # raise
    restaurant = Restaurant.find(params[:id])
    restaurant.update(restaurant_strong_params)
    redirect_to restaurant_path(restaurant)
  end


  private

  def restaurant_strong_params
    params.require(:restaurant).permit(:name, :address, :stars, :admin)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>hello info of the resto</h1>

<%= form_for(@restaurant) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :stars %>
<%= f.number_field :stars %>
<%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p>


<% @restaurants.each do |r| %>
<h1><%= r.name %></h1>
<p><%= r.address %></p>
  <%= r.stars %>
<% end %>

app/views/restaurants/new.html.erb
<!-- <form action="/restaurants" method="post">
<%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="name">name</label>
  <input type="text" name="name">
  <label for="address">address</label>
  <input type="text" name="address">
  <label for="stars">stars</label>
  <input type="text" name="stars">
  <input type="submit" value="add a resto">
</form>
    restaurant = Restaurant.create(name: params[:name],address: params[:address], stars: params[:stars]) -->

<!--
<form action="/restaurants" method="post">
<%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="name">name</label>
  <input type="text" name="restaurant[name]">
  <label for="address">address</label>
  <input type="text" name="restaurant[address]">
  <label for="stars">stars</label>
  <input type="text" name="restaurant[stars]">
  <input type="submit" value="add a resto">
</form> -->
  <!-- # restaurant = Restaurant.create(params[:restaurant]) -->



<%= form_for(@restaurant) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :stars %>
<%= f.number_field :stars %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<%= @restaurant.name %>
<%= @restaurant.address %>
<%= @restaurant.stars %>


<%#= link_to 'delete this resto', restaurant_path(id: @restaurant.id)  %>
<%= link_to 'delete this resto', restaurant_path(@restaurant), method: :delete, data: {confirm: 'are you really sure???'}  %>

<%= link_to 'edit resto', edit_restaurant_path(@restaurant) %>